services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/semakin_6502.sql:/docker-entrypoint-initdb.d/semakin_6502.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

  backend:
    build: ./api
    image: semakin6502-backend
    environment:
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      THROTTLE_TTL: ${THROTTLE_TTL}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}
      FONNTE_TOKEN: ${FONNTE_TOKEN}
      WHATSAPP_API_URL: ${WHATSAPP_API_URL}
      WEB_URL: ${WEB_URL:-}
      REDIS_URL: redis://redis:6379
    ports:
      - "${BACKEND_PORT:-3002}:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./web
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: semakin6502-frontend
    ports:
      - "5173:80"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3002}
    depends_on:
      - backend

volumes:
  mysql-data:
