services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: ${REGISTRY_USERNAME}/semakin6502-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - FONNTE_TOKEN=${FONNTE_TOKEN}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WEB_URL=${WEB_URL:-}
    ports:
      - "${BACKEND_PORT:-3002}:3000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: ${REGISTRY_USERNAME}/semakin6502-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql-data:
