services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/mysql/semakin_6502.sql:/docker-entrypoint-initdb.d/semakin_6502.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 90s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"

  backend:
    image: ${REGISTRY_USERNAME}/semakin6502-backend:latest
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      THROTTLE_TTL: ${THROTTLE_TTL}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}
      FONNTE_TOKEN: ${FONNTE_TOKEN}
      WHATSAPP_API_URL: ${WHATSAPP_API_URL}
      WEB_URL: ${WEB_URL:-}
      REDIS_URL: redis://redis:6379
    ports:
      - "${BACKEND_PORT:-3002}:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: ${REGISTRY_USERNAME}/semakin6502-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3002}
      - VITE_API_URL=${VITE_API_URL:-https://semakin.databenuanta.id/api}
    volumes:
      - ${SSL_CERTIFICATE:?SSL_CERTIFICATE must point to the TLS certificate}:/etc/nginx/certs/tls.crt:ro
      - ${SSL_CERTIFICATE_KEY:?SSL_CERTIFICATE_KEY must point to the TLS private key}:/etc/nginx/certs/tls.key:ro
    depends_on:
      - backend

volumes:
  mysql-data:
