version: '3.9'
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: semakin_6502
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    command: sh -c "npm install && npm run start:dev"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: semakin_6502
      JWT_SECRET: supersecret
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
      THROTTLE_TTL: 900
      THROTTLE_LIMIT: 1000
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql-data:
